// Generates docs/supported-commands.md from the live handler registry.
// Usage: node tools/smoke/src/matrix.ts
import { mkdirSync, writeFileSync } from "node:fs";
import { createDigester, KNOWN_PACKAGES } from "@texdocx/digest";
import { ACCENTS, FUNCTIONS, NARY, SYMBOLS } from "@texdocx/math";

const d = createDigester({});
const visible = (n: string) => !n.startsWith("\u0000") && n.length > 0;
const fmt = (names: Iterable<string>, prefix = "\\") =>
  [...names].filter(visible).sort((a, b) => a.localeCompare(b)).map(n => "`" + prefix + n + "`").join(" ");

const out = `# Supported commands

Generated by \`node tools/smoke/src/matrix.ts\` from the handler registry; do not edit by hand.

## Text and document commands (${[...d.commands.keys()].filter(visible).length})

${fmt(d.commands.keys())}

## Environments (${d.environments.size + 1})

${fmt(["document", ...d.environments.keys()], "")}

## TeX and LaTeX programming layer (${d.e.commands.size + d.e.expandables.size})

${fmt([...d.e.commands.keys(), ...d.e.expandables.keys()])}

## Math (${Object.keys(SYMBOLS).length + Object.keys(NARY).length + Object.keys(FUNCTIONS).length + Object.keys(ACCENTS).length} symbols, operators, functions, accents)

${fmt([...Object.keys(SYMBOLS), ...Object.keys(NARY), ...Object.keys(FUNCTIONS), ...Object.keys(ACCENTS)])}

## Packages accepted without a warning (${KNOWN_PACKAGES.size})

Accepted does not mean every command of the package is implemented; unknown commands still warn.

${fmt(KNOWN_PACKAGES, "")}
`;
mkdirSync("docs", { recursive: true });
writeFileSync("docs/supported-commands.md", out);
console.log("wrote docs/supported-commands.md");
